# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI/CD with Auto-Tag

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [17, 21]

    steps:
    - name: Checkout Repo A
      uses: actions/checkout@v4

    - name: Checkout Repo B
      uses: actions/checkout@v4
      with:
        repository: Lina-Wissem/TEST_CI_CD 
        path: repo-b                              
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java }}
        distribution: temurin
        cache: maven

   # - name: Build with Maven
   #   run: mvn -B package --file repo-b/TEST_CI_CD/process/pom.xml

   # - name: Run Unit Tests
    #  run: mvn -B test --file repo-b/TEST_CI_CD/process/pom.xml

    - name: Upload JAR artifact
      uses: actions/upload-artifact@v4
      with:
        name: my-app-${{ matrix.java }}
        path: repo-b/*.jar

  tag:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Auto Tag
      uses: anothrNick/github-tag-action@1.64.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEFAULT_BUMP: patch  
        
  release:
    needs: tag
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false

  deploy:
    needs: release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: temurin
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: Publish package
      run: mvn deploy -DskipTests --settings $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
